### PR TITLE
 feat : Text Utilities & List Components Added

### PR DESCRIPTION
**Pull request by vikrantkode**
# Open for Reviews
### updated side-nav bar

### CODE REVIEW

**Review by Asuraking1n — COMMENTED** [review]
I guess you didn't added links in your sidebar in text utility page

**Review by kirti2602 — COMMENTED** [review]
Text utilities look fine. But not able to access the list component from sidebar. Please update links

**Review by kirti2602 — COMMENTED** [review]
Everything looks fine. 
Some UI suggestions:- 1) Can have some space medium `checkbox` and text of first list 
                                     2) For stacked list style, show the user that it is stacked by providing some hover effect. You can also keep their alignment on the left side to make it look simpler as notifications generally aren't aligned in the center

**Comment by vikrantkode** [comment]
I will do the needful changes in the UI.
Thank You

**Pull request merged**
